services:
  - type: web
    name: sakura-backend
    env: node
    rootDir: backend
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false

  - type: web
    name: sakura-frontend
    env: static
    rootDir: frontend
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    autoDeploy: true
    envVars:
      - key: VITE_API_URL
        sync: false
      - key: VITE_MEDIA_URL
        sync: false
